//Chiamata con ricerca parametro "s" => nightmare solo per la prima pagina (primi 10 risultati)
GET http://www.omdbapi.com/?apikey=96fcfbd7&s=nightmare HTTP/1.1

###

//Chiamata con ricerca parametro "s" => nightmare solo per la prima pagina (primi 10 risultati)
GET http://www.omdbapi.com/?apikey=96fcfbd7&s=nightmare&page=2 HTTP/1.1

###

//Chiamata con ricerca parametro "s" => terminator SOLO PER I MOVIE
GET http://www.omdbapi.com/?apikey=96fcfbd7&s=terminator&type=movie HTTP/1.1

###

//Chiamata con ricerca parametro "s" => terminator SOLO PER LE SERIE
GET http://www.omdbapi.com/?apikey=96fcfbd7&s=terminator&type=series HTTP/1.1

###

//Chiamata con ricerca parametro "s" => terminator SOLO PER I GIOCHI
GET http://www.omdbapi.com/?apikey=96fcfbd7&s=terminator&type=game HTTP/1.1

###

GET http://www.omdbapi.com/?apikey=96fcfbd7&i=tt0103064

###